### ISSUE TITLE
GDTF does not state which SVG Profile is to be used

### ISSUE THREAD

**Issue by RichardTea** [mvrdevelopment/gdtf-din-spec#42]
I would recommend SVG Tiny 1.2 as this has the widest general support.
Normative reference:
https://www.w3.org/TR/SVGMobile12/

Additionally, there are quite a few features of SVG that are very complex to support, such as animations.
GDTF authoring tools should only expect importers to implement the "Static Features" at the most, if not stricter:
https://www.w3.org/Graphics/SVG/feature/1.2/#SVG-static

**Comment by RichardTea** [comment]
Tiny is the profile that has the greatest support everywhere, both editors in renderers, as it *excludes* most of the esoteric features of "full" SVG.

Almost all renderers target SVG Tiny - eg Qt, most mobile frameworks etc.

If it just says "SVG" then that's implying "full" SVG, latest version (2.0 is in draft), which has several orders of magnitude more features.

**Comment by petrvanekrobe** [comment]
The 1.2 now says:

    Use SVG 1.1 spec
    Don't embed bitmap images.
    Align the viewbox to the top left of the device

And as discussed, this should now be clear.
